### PR TITLE
Support recordRequests parameter for imposter

### PR DESCRIPTION
**Pull request by vinhlh**

### CODE REVIEW

**Comment by vinhlh** [comment]
@demyan112rv can you help to take a look

**Comment by demyan112rv** [comment]
@vinhlh thank you! Merged.

**Comment by demyan112rv** [comment]
@vinhlh I also added new [release](https://github.com/demyan112rv/mountebank-api-php/releases/tag/1.0.2)

**Comment by demyan112rv** [comment]
@vinhlh now we have build error. Give me some time to fix it

**Pull request merged**
